import React, { Component } from 'react';

class Search extends Component {
    render() {
        return (
            <div>
                <div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div><div className="lay_auto">Hello World!</div>
            </div>
        );
    }
}

export default Search;