name: Cypress on Chrome
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  cypress:
    runs-on: ubuntu-20.04
    name: cypress
    
    steps:
    - name: setup node
      uses: actions/checkout@v3

    - name: use node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: print ls
      run: ls

    - name: install dependencies
      run: npm install
    
    - name: creates dotenv
      run: |
        touch .env
        echo REACT_APP_BACK_URL = ${{ secrets.REACT_APP_BACK_URL }}  >> .env
        echo REACT_APP_S3_URL = ${{ secrets.REACT_APP_S3_URL }} >> .env
        echo REACT_APP_CHANNELTALK_PLUGIN_KEY = ${{ secrets.REACT_APP_CHANNELTALK_PLUGIN_KEY }} >> .env

    - name: pm2
      run: |
        npm install pm2 -g
        pm2 start npm -- start

    - name: runs cypress
      uses: cypress-io/github-action@v4
      with:
        browser: chrome

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: video logs
        path: cypress/videos